server:
  port: 9090

spring:
  application:
    name: admin-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
